branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

env:
  global:
    - COMPATHELPER_INTEGRATION_TEST_REPO="bcbi-test/compathelper_integration_test_repo.jl"
    - COMPATHELPER_RUN_INTEGRATION_TESTS="true"
    - JULIA_DEBUG="all"

julia:
  - "1.2"
  - "1.3"

language: julia

os:
  - linux

notifications:
  email: false

## Important note:
## If you want to run the integration tests, make sure that you go into the
## Travis settings for your repository, enable the "Limit concurrent jobs"
## option, and set the number of concurrent jobs to one (1).
## For more details, see https://docs.travis-ci.com/user/customizing-the-build/#limiting-concurrent-jobs

script: julia --code-coverage --inline=no -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  include:
    - stage: VersionVigilante
      if: type = pull_request OR (branch != master and tag IS blank)
      julia: "1.2"
      script:
        - set -e
        - julia -e 'using Pkg; Pkg.add(Pkg.PackageSpec(url = "https://github.com/bcbi/VersionVigilante.jl"))'
        - julia -e 'using VersionVigilante; VersionVigilante.main("https://github.com/bcbi/CompatHelper.jl")'
      after_success: true
