block_labels = [ "DO NOT MERGE" ]

delete_merged_branches = true

status = [
    "Integration/Julia 1/ubuntu-latest/x64",
    "Unit/Julia 1.5.0/ubuntu-latest/x64",
    "Unit/Julia 1.5/ubuntu-latest/x64",
    "Unit/Julia 1/ubuntu-latest/x64",
    "Unit/Julia nightly/ubuntu-latest/x64",
    # "codecov/patch",   # TODO: uncomment this line
    # "codecov/project", # TODO: uncomment this line
    "codecov/project/minimum",
]

timeout_sec = 1800
