name = "CompatHelper"
uuid = "aa819f21-2bde-4658-8897-bab36330d9b7"
authors = ["Dilum Aluthge", "Brown Center for Biomedical Informatics", "contributors"]
version = "3.0.0"

[deps]
GitForge = "8f6bce27-0656-5410-875b-07a5572985df"
Mocking = "78c3b35d-d492-501b-9361-3d52fe80e533"

[compat]
GitForge = "0.1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
